<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddFruitIdForeignkeyToCartItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('cart_items', function (Blueprint $table) {
            // Check if the column exists before adding the foreign key.
            if(Schema::hasColumn('cart_items', 'fruit_id')) {
                $table->foreign('fruit_id')
                ->references('fruit_id')
                ->on('fruits')
                ->onDelete('cascade');
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('cart_items', function (Blueprint $table) {
            // Drop the foreign key constraint.
            // The constraint name is generated by convention: {table}_{column}_foreign
            $table->dropForeign(['fruit_id']);
        });
    }
}
